### ISSUE TITLE
App Models

### ISSUE THREAD

**Issue by leonardk1** [leonardk1/smb#1]
After the initial Review in the [gist](https://gist.github.com/leonardk1/bde5e35ed1801b5d6c71)

These are the Current Models and relationships

#### Models
- Business
- Contact: These are The Different Users in The Business, e.g Accountant, Owner
- Product
- Invoice
- Order: The Request for products or services

##### Business
- Has Many Businesses( This Is Implemented Through a Join Table, where by a business can be both a seller and buyer)
- Has Many Products
- Has Many Contacts
- Has Many Invoices(through orders)
- Has Many Orders

##### Contact
- Belongs To Business

##### Product
- Belongs to Business

##### Orders
- Belongs To Business
- Has One Invoice
- Has Many Products(through order_products)

##### Invoice
- Belongs to Order

**Comment by leonardk1** [comment]
@godfreym @arafatm please review

**Comment by arafatm** [comment]
Why does business have many businesses?

**Comment by leonardk1** [comment]
@arafatm @godfrem The business Has Many Businesses because Those Businesses are the customers(So any Business can have any number of Customers) and any business can be a customer

**Comment by leonardk1** [comment]
![relations](https://cloud.githubusercontent.com/assets/5826646/8954775/922d0eac-35f0-11e5-80b7-78e57ff002c2.jpg)

**Comment by leonardk1** [comment]
@arafatm @godfreym the Many To Many Business relationship is like follow - Follower relationship

**Comment by leonardk1** [comment]
testing integration

**Comment by leonardk1** [comment]
@godfreym @arafatm please review

**Comment by godfreym** [comment]
@leonardk1 I didn't get it on Contact... 
1. owner is the business owner, right? if so then owner can be an attribute of Business entity
2. Accountant by itself is the entity which can have name, phone etc so why is it in Contact entity?

**Comment by leonardk1** [comment]
@godfreym only consider the details on the issue, don't consider the gist anylonger

contact is same as user in this case and contacts shall have roles

just like in oily, we had supervisor, engineers etc

**Comment by leonardk1** [comment]
@godfreym so In this case we can have the following contacts
Owner, accountant etc

**Comment by godfreym** [comment]
@leonardk1 OK i understood but why did you call it Contact and why not User?

**Comment by leonardk1** [comment]
@godfreym It was a name suggested by @arafatm .
but for DMMT, let me change it to user

**Comment by godfreym** [comment]
@leonardk1 Yes it is supposed to be user

**Comment by arafatm** [comment]
@godfreym I'm going to disagree with you. A business has "contacts", not "users". The contacts may not necessarily have a login to the site. But sometimes they use. "User" implies they login.

/cc @leonardk1

**Comment by arafatm** [comment]
@godfreym A business doesn't necessarily have an "owner". Some businesses are publicly held with thousands of shareholders and no owners.

/cc @leonardk1

**Comment by leonardk1** [comment]
@arafatm @godfreym  let me update this in the details

**Comment by godfreym** [comment]
@arafatm Understood

**Comment by leonardk1** [comment]
The

**Comment by leonardk1** [comment]
The initial models have all been set up
